[package]
name = "iris"
version = "0.1.9"
edition = "2024"

[dependencies]
eframe = "0.33.3"
egui_extras = { version = "0.33.3", features = ["all_loaders"] }
image = { version = "0.25.10", features = ["jpeg", "png", "webp", "bmp", "gif", "tiff", "avif"] }
rfd = "0.17.2"
anyhow = "1.0"
arboard = "3.6.1"
arrow-array = "57.2"
chrono = "0.4"
futures = "0.3"
lancedb = "0.26.2"
ort = "2.0.0-rc.12"
rayon = "1.11"
serde_json = "1.0"
tokenizers = "0.23"
tokio = { version = "1.48", features = ["rt-multi-thread"] }
num_cpus = "1.17"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
debug = 1

[profile.release]
opt-level = 3
